name: my first workflow
on: 
  push:
    branches:
      - main 
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greeting
        run: echo "HELLO STRANGER WELCOME TO MY WOLRD"
  job_two:
    needs: job_one
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "good bye"
    
      
